# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MatchHub.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'MatchHub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eMatchHub.proto\"&\n\x13RequestDomainIntent\x12\x0f\n\x07request\x18\x01 \x01(\t\"(\n\x14ResponseDomainIntent\x12\x10\n\x08response\x18\x01 \x01(\t\"!\n\x0eRequestCaption\x12\x0f\n\x07request\x18\x01 \x01(\t\"#\n\x0fResponseCaption\x12\x10\n\x08response\x18\x01 \x01(\t2M\n\rExtractorgRPC\x12<\n\rdomain_intent\x12\x14.RequestDomainIntent\x1a\x15.ResponseDomainIntent2L\n\x13ImageCaptioninggRPC\x12\x35\n\x10generate_caption\x12\x0f.RequestCaption\x1a\x10.ResponseCaptionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MatchHub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTDOMAININTENT']._serialized_start=18
  _globals['_REQUESTDOMAININTENT']._serialized_end=56
  _globals['_RESPONSEDOMAININTENT']._serialized_start=58
  _globals['_RESPONSEDOMAININTENT']._serialized_end=98
  _globals['_REQUESTCAPTION']._serialized_start=100
  _globals['_REQUESTCAPTION']._serialized_end=133
  _globals['_RESPONSECAPTION']._serialized_start=135
  _globals['_RESPONSECAPTION']._serialized_end=170
  _globals['_EXTRACTORGRPC']._serialized_start=172
  _globals['_EXTRACTORGRPC']._serialized_end=249
  _globals['_IMAGECAPTIONINGGRPC']._serialized_start=251
  _globals['_IMAGECAPTIONINGGRPC']._serialized_end=327
# @@protoc_insertion_point(module_scope)
