# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import MatchHub_pb2 as MatchHub__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in MatchHub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExtractorgRPCStub(object):
    """definition of the extracting domain, intent and slot service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.domain_intent = channel.unary_unary(
                '/ExtractorgRPC/domain_intent',
                request_serializer=MatchHub__pb2.RequestDomainIntent.SerializeToString,
                response_deserializer=MatchHub__pb2.ResponseDomainIntent.FromString,
                _registered_method=True)


class ExtractorgRPCServicer(object):
    """definition of the extracting domain, intent and slot service
    """

    def domain_intent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtractorgRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'domain_intent': grpc.unary_unary_rpc_method_handler(
                    servicer.domain_intent,
                    request_deserializer=MatchHub__pb2.RequestDomainIntent.FromString,
                    response_serializer=MatchHub__pb2.ResponseDomainIntent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ExtractorgRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ExtractorgRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExtractorgRPC(object):
    """definition of the extracting domain, intent and slot service
    """

    @staticmethod
    def domain_intent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ExtractorgRPC/domain_intent',
            MatchHub__pb2.RequestDomainIntent.SerializeToString,
            MatchHub__pb2.ResponseDomainIntent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ImageCaptioninggRPCStub(object):
    """definition of image captioning service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.generate_caption = channel.unary_unary(
                '/ImageCaptioninggRPC/generate_caption',
                request_serializer=MatchHub__pb2.RequestCaption.SerializeToString,
                response_deserializer=MatchHub__pb2.ResponseCaption.FromString,
                _registered_method=True)


class ImageCaptioninggRPCServicer(object):
    """definition of image captioning service
    """

    def generate_caption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageCaptioninggRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'generate_caption': grpc.unary_unary_rpc_method_handler(
                    servicer.generate_caption,
                    request_deserializer=MatchHub__pb2.RequestCaption.FromString,
                    response_serializer=MatchHub__pb2.ResponseCaption.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageCaptioninggRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ImageCaptioninggRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageCaptioninggRPC(object):
    """definition of image captioning service
    """

    @staticmethod
    def generate_caption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImageCaptioninggRPC/generate_caption',
            MatchHub__pb2.RequestCaption.SerializeToString,
            MatchHub__pb2.ResponseCaption.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
