syntax = "proto3";

// definition of the extracting domain, intent and slot service
service ExtractorgRPC {
  rpc domain_intent (RequestDomainIntent) returns (ResponseDomainIntent);
}

message RequestDomainIntent {
  string request = 1;
}

message ResponseDomainIntent {
  string response = 1;
}

// definition of image captioning service
service ImageCaptioninggRPC {
  rpc generate_caption (RequestCaption) returns (ResponseCaption);
}

message RequestCaption {
  string request = 1;
}

message ResponseCaption {
  string response = 1;
}
