# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_lab_pb2 as grpc__lab__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_lab_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceAStub(object):
    """Service A definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MethodA = channel.unary_unary(
                '/myservices.ServiceA/MethodA',
                request_serializer=grpc__lab__pb2.RequestA.SerializeToString,
                response_deserializer=grpc__lab__pb2.ResponseA.FromString,
                _registered_method=True)


class ServiceAServicer(object):
    """Service A definition
    """

    def MethodA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceAServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MethodA': grpc.unary_unary_rpc_method_handler(
                    servicer.MethodA,
                    request_deserializer=grpc__lab__pb2.RequestA.FromString,
                    response_serializer=grpc__lab__pb2.ResponseA.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myservices.ServiceA', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myservices.ServiceA', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceA(object):
    """Service A definition
    """

    @staticmethod
    def MethodA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myservices.ServiceA/MethodA',
            grpc__lab__pb2.RequestA.SerializeToString,
            grpc__lab__pb2.ResponseA.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServiceBStub(object):
    """Service B definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MethodB = channel.unary_unary(
                '/myservices.ServiceB/MethodB',
                request_serializer=grpc__lab__pb2.RequestB.SerializeToString,
                response_deserializer=grpc__lab__pb2.ResponseB.FromString,
                _registered_method=True)


class ServiceBServicer(object):
    """Service B definition
    """

    def MethodB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MethodB': grpc.unary_unary_rpc_method_handler(
                    servicer.MethodB,
                    request_deserializer=grpc__lab__pb2.RequestB.FromString,
                    response_serializer=grpc__lab__pb2.ResponseB.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myservices.ServiceB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myservices.ServiceB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceB(object):
    """Service B definition
    """

    @staticmethod
    def MethodB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myservices.ServiceB/MethodB',
            grpc__lab__pb2.RequestB.SerializeToString,
            grpc__lab__pb2.ResponseB.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
