# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_lab.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_lab.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpc_lab.proto\x12\nmyservices\"\x19\n\x08RequestA\x12\r\n\x05param\x18\x01 \x01(\t\"\x1b\n\tResponseA\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x16\n\x08RequestB\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1c\n\tResponseB\x12\x0f\n\x07message\x18\x01 \x01(\t2B\n\x08ServiceA\x12\x36\n\x07MethodA\x12\x14.myservices.RequestA\x1a\x15.myservices.ResponseA2B\n\x08ServiceB\x12\x36\n\x07MethodB\x12\x14.myservices.RequestB\x1a\x15.myservices.ResponseBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_lab_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTA']._serialized_start=30
  _globals['_REQUESTA']._serialized_end=55
  _globals['_RESPONSEA']._serialized_start=57
  _globals['_RESPONSEA']._serialized_end=84
  _globals['_REQUESTB']._serialized_start=86
  _globals['_REQUESTB']._serialized_end=108
  _globals['_RESPONSEB']._serialized_start=110
  _globals['_RESPONSEB']._serialized_end=138
  _globals['_SERVICEA']._serialized_start=140
  _globals['_SERVICEA']._serialized_end=206
  _globals['_SERVICEB']._serialized_start=208
  _globals['_SERVICEB']._serialized_end=274
# @@protoc_insertion_point(module_scope)
